/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Login_Admin = new javax.swing.JButton();
        Label_Pass_Admin = new javax.swing.JLabel();
        Label_Logo_Admin = new javax.swing.JLabel();
        Label_AdminLogin_Admin = new javax.swing.JLabel();
        PassField_Admin = new javax.swing.JPasswordField();
        Button_Back_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Button_Login_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_Admin.setText("LOGIN");
        Button_Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Login_Admin);
        Button_Login_Admin.setBounds(541, 297, 76, 24);

        Label_Pass_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Pass_Admin.setText("PASSWORD");
        getContentPane().add(Label_Pass_Admin);
        Label_Pass_Admin.setBounds(368, 208, 79, 18);

        Label_Logo_Admin.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_Admin.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_Admin);
        Label_Logo_Admin.setBounds(244, 6, 531, 123);

        Label_AdminLogin_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_AdminLogin_Admin.setText("ADMIN LOGIN");
        getContentPane().add(Label_AdminLogin_Admin);
        Label_AdminLogin_Admin.setBounds(434, 141, 129, 23);

        PassField_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(PassField_Admin);
        PassField_Admin.setBounds(368, 244, 249, 23);

        Button_Back_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_Admin.setText("BACK");
        Button_Back_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Back_Admin);
        Button_Back_Admin.setBounds(368, 297, 72, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Login_AdminActionPerformed

    private void PassField_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassField_AdminActionPerformed

    private void Button_Back_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_AdminActionPerformed
        // TODO add your handling code here:
        HomeScreen hs = new HomeScreen();
            hs.setVisible(true);
            hs.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_Admin;
    private javax.swing.JButton Button_Login_Admin;
    private javax.swing.JLabel Label_AdminLogin_Admin;
    private javax.swing.JLabel Label_Logo_Admin;
    private javax.swing.JLabel Label_Pass_Admin;
    private javax.swing.JPasswordField PassField_Admin;
    // End of variables declaration//GEN-END:variables
}
