
import java.awt.Dimension;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Button_Login_Admin = new javax.swing.JButton();
        Label_Pass_Admin = new javax.swing.JLabel();
        Label_Logo_Admin = new javax.swing.JLabel();
        Label_AdminLogin_Admin = new javax.swing.JLabel();
        Admin_Pass = new javax.swing.JPasswordField();
        Button_Back_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 1000));

        Button_Login_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_Admin.setText("LOGIN");
        Button_Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_AdminActionPerformed(evt);
            }
        });

        Label_Pass_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Pass_Admin.setText("PASSWORD");

        Label_Logo_Admin.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_Admin.setText(" GRAND HYATT");

        Label_AdminLogin_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_AdminLogin_Admin.setText("ADMIN LOGIN");

        Admin_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_PassActionPerformed(evt);
            }
        });

        Button_Back_Admin.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_Admin.setText("BACK");
        Button_Back_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(Label_Logo_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(Label_AdminLogin_Admin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Pass_Admin)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Button_Back_Admin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_Login_Admin))
                                .addComponent(Admin_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Label_Logo_Admin)
                .addGap(18, 18, 18)
                .addComponent(Label_AdminLogin_Admin)
                .addGap(44, 44, 44)
                .addComponent(Label_Pass_Admin)
                .addGap(18, 18, 18)
                .addComponent(Admin_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back_Admin)
                    .addComponent(Button_Login_Admin))
                .addContainerGap(651, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 130, 970, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_AdminActionPerformed
        // TODO add your handling code here:
         String AdminPass;
         String pass="Admin";
        AdminPass=this.Admin_Pass.getText();
      
        if(AdminPass!=null){
            
            if(AdminPass.equals(pass))
            
        {
           
            
           /* Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            this.dispose();*/
            
            AdminScreen as = new AdminScreen();
            as.setVisible(true);
            as.setLocationRelativeTo(null);
            this.dispose();
  
        } 
        
            else
                JOptionPane.showMessageDialog(this , "Incorrect Password!!");
            }
    }//GEN-LAST:event_Button_Login_AdminActionPerformed

    private void Admin_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_PassActionPerformed

    private void Button_Back_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_AdminActionPerformed
        // TODO add your handling code here:
        HomeScreen hs = new HomeScreen();
            hs.setVisible(true);
            hs.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Admin_Pass;
    private javax.swing.JButton Button_Back_Admin;
    private javax.swing.JButton Button_Login_Admin;
    private javax.swing.JLabel Label_AdminLogin_Admin;
    private javax.swing.JLabel Label_Logo_Admin;
    private javax.swing.JLabel Label_Pass_Admin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
