/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar(TEST)
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CustomerEntry extends javax.swing.JFrame {
     Connection conn;
    PreparedStatement ps; 
    /**
     * Creates new form Login
     */
    public CustomerEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Logo_CE = new javax.swing.JLabel();
        TextField_Ph_Pri_CE = new javax.swing.JTextField();
        Label_Ph_Pri_CE = new javax.swing.JLabel();
        Button_Login_CE = new javax.swing.JButton();
        Label_CustEntry_CE = new javax.swing.JLabel();
        Button_Back_CE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label_Logo_CE.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_CE.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_CE);
        Label_Logo_CE.setBounds(286, 6, 531, 123);

        TextField_Ph_Pri_CE.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Ph_Pri_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Ph_Pri_CEActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Ph_Pri_CE);
        TextField_Ph_Pri_CE.setBounds(407, 273, 294, 24);

        Label_Ph_Pri_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Pri_CE.setText("PHONE NO.(PRIMARY)");
        getContentPane().add(Label_Ph_Pri_CE);
        Label_Ph_Pri_CE.setBounds(407, 237, 159, 18);

        Button_Login_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_CE.setText("LOGIN");
        Button_Login_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_CEActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Login_CE);
        Button_Login_CE.setBounds(625, 334, 76, 24);

        Label_CustEntry_CE.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_CustEntry_CE.setText("CUSTOMER ENTRY");
        getContentPane().add(Label_CustEntry_CE);
        Label_CustEntry_CE.setBounds(466, 163, 171, 23);

        Button_Back_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_CE.setText("BACK");
        Button_Back_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_CEActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Back_CE);
        Button_Back_CE.setBounds(407, 334, 72, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_Ph_Pri_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Ph_Pri_CEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Ph_Pri_CEActionPerformed

    private void Button_Login_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_CEActionPerformed

        FinalCustomer fc = new FinalCustomer();
            fc.setVisible(true);
            fc.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Login_CEActionPerformed

    private void Button_Back_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_CEActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
            ms.setVisible(true);
            ms.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_CEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_CE;
    private javax.swing.JButton Button_Login_CE;
    private javax.swing.JLabel Label_CustEntry_CE;
    private javax.swing.JLabel Label_Logo_CE;
    private javax.swing.JLabel Label_Ph_Pri_CE;
    private javax.swing.JTextField TextField_Ph_Pri_CE;
    // End of variables declaration//GEN-END:variables
}
