/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class EmployeeLogin extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Label_Logo_EL = new javax.swing.JLabel();
        Label_EmpID_EL = new javax.swing.JLabel();
        Button_Login_EL = new javax.swing.JButton();
        TextField_EmpID_EL = new javax.swing.JTextField();
        Label_Pass_EL = new javax.swing.JLabel();
        Label_Emp_Login_EL = new javax.swing.JLabel();
        TextField_Pass_EL = new javax.swing.JPasswordField();
        Button_Back_EL = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel6.setText("NEW CUSTOMER REGISTRATION");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.darkGray);

        Label_Logo_EL.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_EL.setText(" GRAND HYATT");

        Label_EmpID_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_EmpID_EL.setText("EMPLOYEE ID");

        Button_Login_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_EL.setText("LOGIN");
        Button_Login_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_ELActionPerformed(evt);
            }
        });

        TextField_EmpID_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        TextField_EmpID_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_EmpID_ELActionPerformed(evt);
            }
        });

        Label_Pass_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Pass_EL.setText("PASSWORD");

        Label_Emp_Login_EL.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Emp_Login_EL.setText("EMPLOYEE LOGIN");

        TextField_Pass_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Pass_ELActionPerformed(evt);
            }
        });

        Button_Back_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_EL.setText("BACK");
        Button_Back_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_ELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 205, Short.MAX_VALUE)
                .addComponent(Label_Logo_EL, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_EmpID_EL, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_EmpID_EL)
                            .addComponent(Label_Pass_EL)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Button_Back_EL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_Login_EL))
                                .addComponent(TextField_Pass_EL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(Label_Emp_Login_EL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_Logo_EL)
                .addGap(18, 18, 18)
                .addComponent(Label_Emp_Login_EL)
                .addGap(48, 48, 48)
                .addComponent(Label_EmpID_EL)
                .addGap(18, 18, 18)
                .addComponent(TextField_EmpID_EL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Label_Pass_EL)
                .addGap(18, 18, 18)
                .addComponent(TextField_Pass_EL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back_EL)
                    .addComponent(Button_Login_EL)))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 900, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Login_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_ELActionPerformed

        MainScreen ms = new MainScreen();
            ms.setVisible(true);
            ms.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Login_ELActionPerformed

    private void TextField_EmpID_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_EmpID_ELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmpID_ELActionPerformed

    private void TextField_Pass_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Pass_ELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Pass_ELActionPerformed

    private void Button_Back_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_ELActionPerformed
        // TODO add your handling code here:
        HomeScreen hs = new HomeScreen();
            hs.setVisible(true);
            hs.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_ELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_EL;
    private javax.swing.JButton Button_Login_EL;
    private javax.swing.JLabel Label_EmpID_EL;
    private javax.swing.JLabel Label_Emp_Login_EL;
    private javax.swing.JLabel Label_Logo_EL;
    private javax.swing.JLabel Label_Pass_EL;
    private javax.swing.JTextField TextField_EmpID_EL;
    private javax.swing.JPasswordField TextField_Pass_EL;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
