/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class EmployeeLogin extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Label_Logo_EL = new javax.swing.JLabel();
        Label_EmpID_EL = new javax.swing.JLabel();
        Button_Login_EL = new javax.swing.JButton();
        TextField_EmpID_EL = new javax.swing.JTextField();
        Label_Pass_EL = new javax.swing.JLabel();
        Label_Emp_Login_EL = new javax.swing.JLabel();
        TextField_Pass_EL = new javax.swing.JPasswordField();
        Button_Back_EL = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel6.setText("NEW CUSTOMER REGISTRATION");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label_Logo_EL.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_EL.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_EL);
        Label_Logo_EL.setBounds(272, 6, 531, 123);

        Label_EmpID_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_EmpID_EL.setText("EMPLOYEE ID");
        getContentPane().add(Label_EmpID_EL);
        Label_EmpID_EL.setBounds(397, 228, 98, 18);

        Button_Login_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_EL.setText("LOGIN");
        Button_Login_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_ELActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Login_EL);
        Button_Login_EL.setBounds(615, 400, 76, 24);

        TextField_EmpID_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        TextField_EmpID_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_EmpID_ELActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_EmpID_EL);
        TextField_EmpID_EL.setBounds(397, 252, 294, 24);

        Label_Pass_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Pass_EL.setText("PASSWORD");
        getContentPane().add(Label_Pass_EL);
        Label_Pass_EL.setBounds(397, 315, 79, 18);

        Label_Emp_Login_EL.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Emp_Login_EL.setText("EMPLOYEE LOGIN");
        getContentPane().add(Label_Emp_Login_EL);
        Label_Emp_Login_EL.setBounds(458, 157, 166, 23);

        TextField_Pass_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Pass_ELActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Pass_EL);
        TextField_Pass_EL.setBounds(397, 339, 294, 23);

        Button_Back_EL.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_EL.setText("BACK");
        Button_Back_EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_ELActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Back_EL);
        Button_Back_EL.setBounds(397, 400, 72, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Login_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_ELActionPerformed

        MainScreen ms = new MainScreen();
            ms.setVisible(true);
            ms.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Login_ELActionPerformed

    private void TextField_EmpID_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_EmpID_ELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmpID_ELActionPerformed

    private void TextField_Pass_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Pass_ELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Pass_ELActionPerformed

    private void Button_Back_ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_ELActionPerformed
        // TODO add your handling code here:
        HomeScreen hs = new HomeScreen();
            hs.setVisible(true);
            hs.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_ELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_EL;
    private javax.swing.JButton Button_Login_EL;
    private javax.swing.JLabel Label_EmpID_EL;
    private javax.swing.JLabel Label_Emp_Login_EL;
    private javax.swing.JLabel Label_Logo_EL;
    private javax.swing.JLabel Label_Pass_EL;
    private javax.swing.JTextField TextField_EmpID_EL;
    private javax.swing.JPasswordField TextField_Pass_EL;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
