/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
public class FinalCustomer extends javax.swing.JFrame {

    /**
     * Creates new form FinalCustomer
     */
    public FinalCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jComboBox2 = new javax.swing.JComboBox<>();
        Label_Logo_FC = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_CustDets_FC = new javax.swing.JTable();
        Label_Room_Allot_FC = new javax.swing.JLabel();
        Label_ServiceDets_FC = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_RoomDets_FC = new javax.swing.JTable();
        Label_RoomDets_FC = new javax.swing.JLabel();
        Label_Service_Name_FC = new javax.swing.JLabel();
        Label_Service_Rate_FC = new javax.swing.JLabel();
        Button_Enter_ServiceDets_FC = new javax.swing.JButton();
        TextField_Service_Name_FC = new javax.swing.JTextField();
        TextField_Service_Rate_FC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Services_Used_FC = new javax.swing.JTable();
        Label_Via_FC = new javax.swing.JLabel();
        TextField_ToPay_FC = new javax.swing.JTextField();
        Label_ToPay_FC = new javax.swing.JLabel();
        ComboBox_Via_FC = new javax.swing.JComboBox<>();
        Button_LogOut_FC = new javax.swing.JButton();
        Label_CustDets_FC = new javax.swing.JLabel();
        Label_CheckIN_FC = new javax.swing.JLabel();
        Label_Room_Type_FC = new javax.swing.JLabel();
        Label_Check_Out_FC = new javax.swing.JLabel();
        Label_Nos_Adults_FC = new javax.swing.JLabel();
        ComboBox_Room_Typr_FC = new javax.swing.JComboBox<>();
        TextField_CheckIN_FC = new javax.swing.JTextField();
        TextField_Check_Out_FC = new javax.swing.JTextField();
        TextField_Nos_Adults_FC = new javax.swing.JTextField();
        Label_Nos_Children_FC = new javax.swing.JLabel();
        TextField_Nos_Children_FC = new javax.swing.JTextField();
        Label_Services_Used_FC = new javax.swing.JLabel();

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FNAME", "MNAME", "LNAME", "AADHAR", "PH. PRI", "PH. SEC", "EMAIL", "ADDRESS", "GENDER", "MARRIAGE", "DOB"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD", "DEBIT CARD", "CHEQUE" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label_Logo_FC.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_FC.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_FC);
        Label_Logo_FC.setBounds(290, 10, 531, 123);

        Table_CustDets_FC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FNAME", "MNAME", "LNAME", "AADHAR", "PH. PRI", "PH. SEC", "EMAIL", "ADDRESS", "GENDER", "MARRIAGE", "DOB"
            }
        ));
        jScrollPane6.setViewportView(Table_CustDets_FC);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(0, 170, 1032, 74);

        Label_Room_Allot_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Room_Allot_FC.setText("ROOM ALLOTMENT");
        getContentPane().add(Label_Room_Allot_FC);
        Label_Room_Allot_FC.setBounds(461, 290, 179, 23);

        Label_ServiceDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_ServiceDets_FC.setText("SERVICES DETAILS");
        getContentPane().add(Label_ServiceDets_FC);
        Label_ServiceDets_FC.setBounds(459, 619, 173, 23);

        Table_RoomDets_FC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM NO.", "TYPE", "STATUS", "RATE"
            }
        ));
        jScrollPane4.setViewportView(Table_RoomDets_FC);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(6, 541, 1020, 60);

        Label_RoomDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_RoomDets_FC.setText("ROOM DETAILS");
        getContentPane().add(Label_RoomDets_FC);
        Label_RoomDets_FC.setBounds(477, 512, 141, 23);

        Label_Service_Name_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Name_FC.setText("SERVICE NAME");
        getContentPane().add(Label_Service_Name_FC);
        Label_Service_Name_FC.setBounds(382, 690, 108, 18);

        Label_Service_Rate_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Rate_FC.setText("SERVICE RATE");
        getContentPane().add(Label_Service_Rate_FC);
        Label_Service_Rate_FC.setBounds(382, 744, 102, 18);

        Button_Enter_ServiceDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Enter_ServiceDets_FC.setText("ENTER");
        Button_Enter_ServiceDets_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Enter_ServiceDets_FCActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Enter_ServiceDets_FC);
        Button_Enter_ServiceDets_FC.setBounds(509, 804, 78, 23);
        getContentPane().add(TextField_Service_Name_FC);
        TextField_Service_Name_FC.setBounds(554, 685, 130, 23);

        TextField_Service_Rate_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Service_Rate_FCActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Service_Rate_FC);
        TextField_Service_Rate_FC.setBounds(554, 739, 130, 23);

        Table_Services_Used_FC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "RATE", "DATE", "TIME"
            }
        ));
        jScrollPane1.setViewportView(Table_Services_Used_FC);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 916, 1020, 346);

        Label_Via_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Via_FC.setText("VIA");
        getContentPane().add(Label_Via_FC);
        Label_Via_FC.setBounds(410, 1380, 66, 23);

        TextField_ToPay_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ToPay_FCActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_ToPay_FC);
        TextField_ToPay_FC.setBounds(515, 1327, 179, 23);

        Label_ToPay_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_ToPay_FC.setText("TO PAY");
        getContentPane().add(Label_ToPay_FC);
        Label_ToPay_FC.setBounds(410, 1329, 66, 23);

        ComboBox_Via_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        ComboBox_Via_FC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD", "DEBIT CARD", "CHEQUE" }));
        getContentPane().add(ComboBox_Via_FC);
        ComboBox_Via_FC.setBounds(515, 1380, 179, 24);

        Button_LogOut_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_LogOut_FC.setText("LOG OUT");
        Button_LogOut_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogOut_FCActionPerformed(evt);
            }
        });
        getContentPane().add(Button_LogOut_FC);
        Button_LogOut_FC.setBounds(930, 1430, 92, 24);

        Label_CustDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_CustDets_FC.setText("CUSTOMER DETAILS");
        getContentPane().add(Label_CustDets_FC);
        Label_CustDets_FC.setBounds(458, 135, 188, 23);

        Label_CheckIN_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_CheckIN_FC.setText("CHECK IN DATE");
        getContentPane().add(Label_CheckIN_FC);
        Label_CheckIN_FC.setBounds(253, 449, 114, 18);

        Label_Room_Type_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Room_Type_FC.setText("ROOM TYPE");
        getContentPane().add(Label_Room_Type_FC);
        Label_Room_Type_FC.setBounds(253, 361, 83, 18);

        Label_Check_Out_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Check_Out_FC.setText("CHECK OUT DATE");
        getContentPane().add(Label_Check_Out_FC);
        Label_Check_Out_FC.setBounds(624, 454, 127, 18);

        Label_Nos_Adults_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Nos_Adults_FC.setText("NUMBER OF ADULTS");
        getContentPane().add(Label_Nos_Adults_FC);
        Label_Nos_Adults_FC.setBounds(253, 405, 146, 18);

        ComboBox_Room_Typr_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        ComboBox_Room_Typr_FC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "DELUXE", "SUITE", " " }));
        getContentPane().add(ComboBox_Room_Typr_FC);
        ComboBox_Room_Typr_FC.setBounds(449, 358, 105, 24);

        TextField_CheckIN_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_CheckIN_FCActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_CheckIN_FC);
        TextField_CheckIN_FC.setBounds(451, 449, 105, 23);
        getContentPane().add(TextField_Check_Out_FC);
        TextField_Check_Out_FC.setBounds(820, 449, 100, 23);
        getContentPane().add(TextField_Nos_Adults_FC);
        TextField_Nos_Adults_FC.setBounds(451, 400, 105, 23);

        Label_Nos_Children_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Nos_Children_FC.setText("NUMBER OF CHILDREN");
        getContentPane().add(Label_Nos_Children_FC);
        Label_Nos_Children_FC.setBounds(624, 405, 167, 18);
        getContentPane().add(TextField_Nos_Children_FC);
        TextField_Nos_Children_FC.setBounds(820, 400, 100, 23);

        Label_Services_Used_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Services_Used_FC.setText("SERVICES USED");
        getContentPane().add(Label_Services_Used_FC);
        Label_Services_Used_FC.setBounds(477, 875, 143, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Enter_ServiceDets_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Enter_ServiceDets_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Enter_ServiceDets_FCActionPerformed

    private void TextField_Service_Rate_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Service_Rate_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Service_Rate_FCActionPerformed

    private void TextField_ToPay_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ToPay_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ToPay_FCActionPerformed

    private void Button_LogOut_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogOut_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_LogOut_FCActionPerformed

    private void TextField_CheckIN_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CheckIN_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CheckIN_FCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Enter_ServiceDets_FC;
    private javax.swing.JButton Button_LogOut_FC;
    private javax.swing.JComboBox<String> ComboBox_Room_Typr_FC;
    private javax.swing.JComboBox<String> ComboBox_Via_FC;
    private javax.swing.JLabel Label_CheckIN_FC;
    private javax.swing.JLabel Label_Check_Out_FC;
    private javax.swing.JLabel Label_CustDets_FC;
    private javax.swing.JLabel Label_Logo_FC;
    private javax.swing.JLabel Label_Nos_Adults_FC;
    private javax.swing.JLabel Label_Nos_Children_FC;
    private javax.swing.JLabel Label_RoomDets_FC;
    private javax.swing.JLabel Label_Room_Allot_FC;
    private javax.swing.JLabel Label_Room_Type_FC;
    private javax.swing.JLabel Label_ServiceDets_FC;
    private javax.swing.JLabel Label_Service_Name_FC;
    private javax.swing.JLabel Label_Service_Rate_FC;
    private javax.swing.JLabel Label_Services_Used_FC;
    private javax.swing.JLabel Label_ToPay_FC;
    private javax.swing.JLabel Label_Via_FC;
    private javax.swing.JTable Table_CustDets_FC;
    private javax.swing.JTable Table_RoomDets_FC;
    private javax.swing.JTable Table_Services_Used_FC;
    private javax.swing.JTextField TextField_CheckIN_FC;
    private javax.swing.JTextField TextField_Check_Out_FC;
    private javax.swing.JTextField TextField_Nos_Adults_FC;
    private javax.swing.JTextField TextField_Nos_Children_FC;
    private javax.swing.JTextField TextField_Service_Name_FC;
    private javax.swing.JTextField TextField_Service_Rate_FC;
    private javax.swing.JTextField TextField_ToPay_FC;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
