/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class HomeScreen extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps;
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Label_Logo_HS = new javax.swing.JLabel();
        Button_Emp_Login_HS = new javax.swing.JButton();
        Button_Admin_Login_HS = new javax.swing.JButton();
        Label_Emp_Login_HS = new javax.swing.JLabel();
        Label_Admin_Login_HS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label_Logo_HS.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_HS.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_HS);
        Label_Logo_HS.setBounds(230, 10, 531, 123);

        Button_Emp_Login_HS.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Emp_Login_HS.setText("LOGIN");
        Button_Emp_Login_HS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Emp_Login_HSActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Emp_Login_HS);
        Button_Emp_Login_HS.setBounds(273, 291, 76, 24);

        Button_Admin_Login_HS.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Admin_Login_HS.setText("LOGIN");
        Button_Admin_Login_HS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Admin_Login_HSActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Admin_Login_HS);
        Button_Admin_Login_HS.setBounds(654, 291, 76, 24);

        Label_Emp_Login_HS.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Emp_Login_HS.setText("EMPLOYEE LOGIN");
        getContentPane().add(Label_Emp_Login_HS);
        Label_Emp_Login_HS.setBounds(240, 250, 166, 23);

        Label_Admin_Login_HS.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Admin_Login_HS.setText("ADMIN LOGIN");
        getContentPane().add(Label_Admin_Login_HS);
        Label_Admin_Login_HS.setBounds(633, 256, 129, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Admin_Login_HSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Admin_Login_HSActionPerformed

        Admin ad = new Admin();
            ad.setVisible(true);
            ad.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Admin_Login_HSActionPerformed

    private void Button_Emp_Login_HSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Emp_Login_HSActionPerformed

        EmployeeLogin el = new EmployeeLogin();
            el.setVisible(true);
            el.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Emp_Login_HSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Admin_Login_HS;
    private javax.swing.JButton Button_Emp_Login_HS;
    private javax.swing.JLabel Label_Admin_Login_HS;
    private javax.swing.JLabel Label_Emp_Login_HS;
    private javax.swing.JLabel Label_Logo_HS;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
