

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

        
public class Registration extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps; 
    
    /**
     * Creates new form Rushi1
     */
    public Registration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new javax.swing.JButton();
        TextField_Fname_NCR = new javax.swing.JTextField();
        Label_Name_NCR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Label_Logo_NCR = new javax.swing.JLabel();
        Label_NCR = new javax.swing.JLabel();
        TextField_Mname_NCR = new javax.swing.JTextField();
        TextField_Lname_NCR = new javax.swing.JTextField();
        Label_Fname_NCR = new javax.swing.JLabel();
        Label_Mname_NCR = new javax.swing.JLabel();
        Label_Lname_NCR = new javax.swing.JLabel();
        Label_Ph_Pri_NCR = new javax.swing.JLabel();
        TextField_Ph_Pri_NCR = new javax.swing.JTextField();
        TextField_Email_NCR = new javax.swing.JTextField();
        Label_Ph_Sec_NCR = new javax.swing.JLabel();
        Label_Email_NCR = new javax.swing.JLabel();
        TextField_Ph_Sec_NCR = new javax.swing.JTextField();
        Label_Aadhar_NCR = new javax.swing.JLabel();
        Label_DOB_NCR = new javax.swing.JLabel();
        TextField_DOB_NCR = new javax.swing.JTextField();
        TextField_Aadhar_NCR = new javax.swing.JTextField();
        Label_Marr_Status_NCR = new javax.swing.JLabel();
        RadioButton_Yes_Marr_Status_NCR = new javax.swing.JRadioButton();
        RadioButton_No_Marr_Status_NCR = new javax.swing.JRadioButton();
        Label_Gender_NCR = new javax.swing.JLabel();
        RadioButton_Male_Gender_NCR = new javax.swing.JRadioButton();
        RadioButton_Female_Gender_NCR = new javax.swing.JRadioButton();
        Button_Register_NCR = new javax.swing.JButton();
        Button_Back_NCR = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        register.setText("SIGN UP");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(864, 823, 81, 23);

        TextField_Fname_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Fname_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Fname_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Fname_NCR);
        TextField_Fname_NCR.setBounds(448, 253, 90, 24);

        Label_Name_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Name_NCR.setText("NAME");
        getContentPane().add(Label_Name_NCR);
        Label_Name_NCR.setBounds(448, 226, 44, 18);

        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(868, 707, 72, 17);
        getContentPane().add(password);
        password.setBounds(868, 730, 64, 23);

        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpassword);
        confirmpassword.setBounds(873, 788, 64, 23);

        jLabel4.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(839, 765, 134, 17);

        Label_Logo_NCR.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_NCR.setText(" GRAND HYATT");
        getContentPane().add(Label_Logo_NCR);
        Label_Logo_NCR.setBounds(343, 6, 531, 123);

        Label_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_NCR.setText("NEW CUSTOMER REGISTRATION");
        getContentPane().add(Label_NCR);
        Label_NCR.setBounds(448, 141, 296, 23);

        TextField_Mname_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        getContentPane().add(TextField_Mname_NCR);
        TextField_Mname_NCR.setBounds(550, 253, 90, 24);

        TextField_Lname_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Lname_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Lname_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Lname_NCR);
        TextField_Lname_NCR.setBounds(652, 253, 90, 24);

        Label_Fname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Fname_NCR.setText("FIRST");
        getContentPane().add(Label_Fname_NCR);
        Label_Fname_NCR.setBounds(471, 283, 41, 18);

        Label_Mname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Mname_NCR.setText("MIDDLE");
        getContentPane().add(Label_Mname_NCR);
        Label_Mname_NCR.setBounds(570, 283, 60, 18);

        Label_Lname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Lname_NCR.setText("LAST");
        getContentPane().add(Label_Lname_NCR);
        Label_Lname_NCR.setBounds(688, 283, 35, 18);

        Label_Ph_Pri_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Pri_NCR.setText("PHONE NO.(PRIMARY)");
        getContentPane().add(Label_Ph_Pri_NCR);
        Label_Ph_Pri_NCR.setBounds(448, 322, 159, 18);

        TextField_Ph_Pri_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Ph_Pri_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Ph_Pri_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Ph_Pri_NCR);
        TextField_Ph_Pri_NCR.setBounds(448, 352, 294, 24);

        TextField_Email_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Email_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Email_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Email_NCR);
        TextField_Email_NCR.setBounds(448, 496, 294, 24);

        Label_Ph_Sec_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Sec_NCR.setText("PHONE NO.(SECONDARY)");
        getContentPane().add(Label_Ph_Sec_NCR);
        Label_Ph_Sec_NCR.setBounds(448, 400, 178, 18);

        Label_Email_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Email_NCR.setText("EMAIL ID");
        getContentPane().add(Label_Email_NCR);
        Label_Email_NCR.setBounds(448, 472, 68, 18);

        TextField_Ph_Sec_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Ph_Sec_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Ph_Sec_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Ph_Sec_NCR);
        TextField_Ph_Sec_NCR.setBounds(448, 430, 294, 24);

        Label_Aadhar_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Aadhar_NCR.setText("AADHAR NUMBER");
        getContentPane().add(Label_Aadhar_NCR);
        Label_Aadhar_NCR.setBounds(450, 538, 130, 20);

        Label_DOB_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_DOB_NCR.setText("DATE OF BIRTH");
        getContentPane().add(Label_DOB_NCR);
        Label_DOB_NCR.setBounds(450, 604, 110, 20);

        TextField_DOB_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_DOB_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DOB_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_DOB_NCR);
        TextField_DOB_NCR.setBounds(450, 630, 294, 24);

        TextField_Aadhar_NCR.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Aadhar_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Aadhar_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Aadhar_NCR);
        TextField_Aadhar_NCR.setBounds(450, 564, 294, 24);

        Label_Marr_Status_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Marr_Status_NCR.setText("MARRIAGE STATUS");
        getContentPane().add(Label_Marr_Status_NCR);
        Label_Marr_Status_NCR.setBounds(450, 672, 135, 20);

        RadioButton_Yes_Marr_Status_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        RadioButton_Yes_Marr_Status_NCR.setText("YES");
        getContentPane().add(RadioButton_Yes_Marr_Status_NCR);
        RadioButton_Yes_Marr_Status_NCR.setBounds(450, 698, 48, 22);

        RadioButton_No_Marr_Status_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        RadioButton_No_Marr_Status_NCR.setText("NO");
        RadioButton_No_Marr_Status_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_No_Marr_Status_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton_No_Marr_Status_NCR);
        RadioButton_No_Marr_Status_NCR.setBounds(541, 698, 44, 22);

        Label_Gender_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Gender_NCR.setText("GENDER");
        getContentPane().add(Label_Gender_NCR);
        Label_Gender_NCR.setBounds(450, 738, 60, 20);

        RadioButton_Male_Gender_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        RadioButton_Male_Gender_NCR.setText("MALE");
        getContentPane().add(RadioButton_Male_Gender_NCR);
        RadioButton_Male_Gender_NCR.setBounds(450, 764, 65, 22);

        RadioButton_Female_Gender_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        RadioButton_Female_Gender_NCR.setText("FEMALE");
        RadioButton_Female_Gender_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_Female_Gender_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton_Female_Gender_NCR);
        RadioButton_Female_Gender_NCR.setBounds(537, 764, 83, 22);

        Button_Register_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Register_NCR.setText("REGISTER");
        Button_Register_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Register_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Register_NCR);
        Button_Register_NCR.setBounds(644, 825, 100, 24);

        Button_Back_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_NCR.setText("BACK");
        Button_Back_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_NCRActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Back_NCR);
        Button_Back_NCR.setBounds(450, 825, 72, 24);
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(1190, 0, 10, 994);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_Fname_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Fname_NCRActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextField_Fname_NCRActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String User_name;
        User_name=this.TextField_Fname_NCR.getText();
        String password;
        password=this.password.getText();
        String confirmpassword;
        confirmpassword=this.confirmpassword.getText();
        System.out.println("Hello");
        if(User_name!=null && password!=null){
            System.out.println(User_name +" "+password);
            if(password.equals(confirmpassword)){
            try
        {
            conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/Trial?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("insert into Users(User_name,password) values(?,?)");
            ps.setString(1, User_name);
            ps.setString(2 ,password);
            ps.executeUpdate();
            
           /* Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            this.dispose();*/
            
            HomeScreen h = new HomeScreen();
            h.setVisible(true);
            h.setLocationRelativeTo(null);
            this.dispose();
  
        } catch(SQLException ex)
            {
            System.err.println(ex);
            }
        }
            else
                JOptionPane.showMessageDialog(this , "Password is not the same ma boi!!");
            }
    }//GEN-LAST:event_registerActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        
        if(password==confirmpassword)
        {
            
        }
    }//GEN-LAST:event_registerMouseClicked

    private void TextField_Lname_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Lname_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Lname_NCRActionPerformed

    private void TextField_Ph_Pri_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Ph_Pri_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Ph_Pri_NCRActionPerformed

    private void TextField_Email_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Email_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Email_NCRActionPerformed

    private void TextField_Ph_Sec_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Ph_Sec_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Ph_Sec_NCRActionPerformed

    private void TextField_DOB_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DOB_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DOB_NCRActionPerformed

    private void TextField_Aadhar_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Aadhar_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Aadhar_NCRActionPerformed

    private void RadioButton_Female_Gender_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_Female_Gender_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_Female_Gender_NCRActionPerformed

    private void RadioButton_No_Marr_Status_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_No_Marr_Status_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_No_Marr_Status_NCRActionPerformed

    private void Button_Register_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Register_NCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Register_NCRActionPerformed

    private void Button_Back_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_NCRActionPerformed
        // TODO add your handling code here:
         CustomerEntry ce = new CustomerEntry();
            ce.setVisible(true);
            ce.setLocationRelativeTo(null);
            this.dispose();

    }//GEN-LAST:event_Button_Back_NCRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_NCR;
    private javax.swing.JButton Button_Register_NCR;
    private javax.swing.JLabel Label_Aadhar_NCR;
    private javax.swing.JLabel Label_DOB_NCR;
    private javax.swing.JLabel Label_Email_NCR;
    private javax.swing.JLabel Label_Fname_NCR;
    private javax.swing.JLabel Label_Gender_NCR;
    private javax.swing.JLabel Label_Lname_NCR;
    private javax.swing.JLabel Label_Logo_NCR;
    private javax.swing.JLabel Label_Marr_Status_NCR;
    private javax.swing.JLabel Label_Mname_NCR;
    private javax.swing.JLabel Label_NCR;
    private javax.swing.JLabel Label_Name_NCR;
    private javax.swing.JLabel Label_Ph_Pri_NCR;
    private javax.swing.JLabel Label_Ph_Sec_NCR;
    private javax.swing.JRadioButton RadioButton_Female_Gender_NCR;
    private javax.swing.JRadioButton RadioButton_Male_Gender_NCR;
    private javax.swing.JRadioButton RadioButton_No_Marr_Status_NCR;
    private javax.swing.JRadioButton RadioButton_Yes_Marr_Status_NCR;
    private javax.swing.JTextField TextField_Aadhar_NCR;
    private javax.swing.JTextField TextField_DOB_NCR;
    private javax.swing.JTextField TextField_Email_NCR;
    private javax.swing.JTextField TextField_Fname_NCR;
    private javax.swing.JTextField TextField_Lname_NCR;
    private javax.swing.JTextField TextField_Mname_NCR;
    private javax.swing.JTextField TextField_Ph_Pri_NCR;
    private javax.swing.JTextField TextField_Ph_Sec_NCR;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables

    private String getText111() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
